FROM golang:1.8-alpine

RUN apk add --update git make gcc musl-dev
RUN go get github.com/rancher/trash

WORKDIR /go/src/github.com/docker/docker-e2e
VOLUME [ "/go/src/github.com/docker/docker-e2e/build" ]
CMD make build-binaries

COPY . ./
RUN trash  # Force updating the vendored sources per spec; this slows the build but is most correct.
